cc_library(
    name = "httpconn_lib",
    srcs = ["http_conn.cpp"],
    hdrs = ["http_conn.h"],
    deps = [ 
	"//commen:commen_lib",
	"//log:log_lib",
	],

    visibility = ["//visibility:public"],

)
