cc_library(
    name = "httpserver_lib",
    srcs = ["httpServer.cpp"],
    hdrs = ["httpServer.h"],
    deps = [ 
	"//log:log_lib",
	"//commen:commen_lib",
	"//httpconn:httpconn_lib",	
	"//threadpool:threadpool_lib",
	],
   visibility = ["//visibility:public"],

)
